Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"

Metrics/ClassLength:
  CountAsOne: ["array", "hereodoc", "hash", "method_call"]

Metrics/ParameterLists:
  Max: 7

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
