name: PCO Release - Create Release on PR Merge
description: Automates the creation of a release when a `PCO-Release` PR is merged.

inputs:
  NODE_AUTH_TOKEN:
    description: "The NPM auth token to use for publishing"
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
    - run: yarn install
      shell: bash
    # Create an RC release
    - run: ./node_modules/.bin/lerna publish --canary --conventional-prerelease --conventionalCommits --preid=rc --dist-tag=next --json -y
      shell: bash
      id: lerna_publish
