name: PCO Release - Release by PR
description: A tool for creating and managing releases for PCO projects through Pull Requests.

inputs:
  GITHUB_TOKEN:
    description: token for access
    required: true
  release_type:
    required: false
  install-command:
    description: 'The script command to use to install the package\'s dependencies'
    required: false
    type: string
    default: 'yarn install --check-files'

runs:
  using: 'node20'
  main: 'dist/index.js'
