name: PCO Release - Release by PR
description: A tool for creating and managing releases for PCO projects through Pull Requests.

inputs:
  GITHUB_TOKEN:
    description: token for access
    required: false
  app-id:
    description: 'The app id for the github app'
    required: false
  private-key:
    description: 'The private key for the github app'
    required: false
  release-type:
    required: false
  install-command:
    description: "The script command to use to install the package's dependencies"
    required: false
    type: string
    default: 'yarn install --check-files'

runs:
  using: 'composite'
  steps:
    - name: Generate a token
      if: ${{ inputs.app-id && inputs.private-key }}
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
    - name: Run release by PR
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token || inputs.GITHUB_TOKEN }}
        INPUT_RELEASE-TYPE: ${{ inputs.release-type }}
        INPUT_INSTALL-COMMAND: ${{ inputs.install-command }}
