name: PCO Release - Release by PR
description: A tool for creating and managing releases for PCO projects through Pull Requests.

inputs:
  GITHUB_TOKEN:
    description: token for access
    required: false
  app-id:
    description: 'The app id for the github app'
    required: false
  private-key:
    description: 'The private key for the github app'
    required: false
  release_type:
    required: false
    default: nochange
  package_json_path:
    description: 'The path to the package.json file to version.'
    required: false
    default: 'package.json'
  version_command:
    description: 'The command to run to bump the version'
    required: false
    default: 'yarn version'

runs:
  using: 'composite'
  steps:
    - name: Generate a token
      if: ${{ !inputs.GITHUB_TOKEN }}
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
        repositories: ${{ github.repository }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Enable Corepack
      shell: bash
      run: export COREPACK_ENABLE_DOWNLOAD_PROMPT=0 && corepack enable
    - name: Run release by PR
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN || steps.generate-token.outputs.token }}
        INPUT_RELEASE_TYPE: ${{ inputs.release_type }}
        INPUT_PACKAGE_JSON_PATH: ${{ inputs.package_json_path }}
        INPUT_VERSION_COMMAND: ${{ inputs.version_command }}
