name: "PCO Release Deploy"
description: "Deploys updates of a new release to all planningcenter repos that have a package as its dependency"
inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  owner:
    description: "Owner of the repositories"
    required: false
    default: "planningcenter"
  only:
    description: "Only run on specific repos. This is a comma separated list of repo names (ie 'people,services,groups')"
    required: false
    default: ""
  package-name:
    description: "The name of the package to update"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Find Repos to update
      id: find-repos
      shell: bash
      run: |
        PAGE=1
        REPOS=()
        IFS=',' read -r -a ONLY_REPOS <<< "${{ inputs.only }}"

        while : ; do
          URL="https://api.github.com/orgs/${{ inputs.owner }}/repos?&per_page=100&page=$PAGE"
          echo "URL: $URL"
          RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" $URL)
          CURRENT_PAGE_REPOS=$(echo "$RESPONSE" | jq -r '.[] | select(.archived == false) | .name')
          if [[ -z "$CURRENT_PAGE_REPOS" ]]; then
            break # Exit loop if no more repos
          fi
          for REPO in $CURRENT_PAGE_REPOS; do
            if [[ -n "${{ inputs.only }}" ]]; then
              if printf '%s\n' "${ONLY_REPOS[@]}" | grep -qx "$REPO"; then
                REPOS+=("$REPO")
              fi
            else
              REPOS+=("$REPO")
            fi
          done
          ((PAGE++))
        done

        PACKAGE_NAME="${{ inputs.package-name }}"
        FILTERED_REPOS=()
        for REPO in "${REPOS[@]}"; do
          DEPENDENCY_FILE_CONTENT=""
          if DEPENDENCY_FILE_CONTENT=$(gh api repos/${{ inputs.owner }}/$REPO/contents/package.json --jq '.content' 2>/dev/null); then
            DEPENDENCY_FILE=$(echo "$DEPENDENCY_FILE_CONTENT" | base64 --decode)
            if [[ $DEPENDENCY_FILE == *"$PACKAGE_NAME"* ]]; then
              FILTERED_REPOS+=("$REPO")
            fi
          fi
        done
        REPO_LIST=$(IFS=,; echo "${FILTERED_REPOS[*]}")
        echo "::set-output name=repo_list::$REPO_LIST"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
