source "https://rubygems.org"

gem "base64"
gem "dependabot-omnibus", "~> 0.316.0"
gem "octokit"
gem "ostruct"

group :development, :test do
  gem "byebug"
  gem "faraday-multipart"
  gem "faraday-retry"
  gem "rspec"
  gem "webmock"
end
