name: PCO Release - Create Release on PR Merge
description: Automates the creation of a release when a `PCO-Release` PR is merged.

# inputs:
#   package_json_path:
#     description: "The path to the package.json file to version."
#     required: false
#     default: "package.json"

runs:
  using: "composite"
  steps:
    - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
      shell: bash
    - run: yarn install
      shell: bash
    - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash
    - run: git config --global user.name "github-actions[bot]"
      shell: bash
    - shell: bash
      run: |
        if git rev-parse --verify pco-release--internal > /dev/null 2>&1; then
          git checkout pco-release--internal
        else
          git checkout -b pco-release--internal
          git commit --allow-empty -m "New release branch"
        fi
    - run: git rebase origin/main --strategy-option=theirs
      shell: bash
    - run: git push -f --set-upstream origin pco-release--internal
      shell: bash
    - run: npm whoami
      shell: bash
    - run: ./node_modules/.bin/lerna publish --canary --conventional-prerelease --conventionalCommits --preid=rc --dist-tag=next --json -y
      shell: bash
