name: PCO-Release - Lerna Release PR
on:
  workflow_call:

jobs:
  create-rc-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PLANNINGCENTER_NPM_TOKEN }}
      - run: yarn install
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: |
          if git rev-parse --verify origin/pco-release--internal-rc > /dev/null 2>&1; then
            git checkout pco-release--internal-rc
          else
            git checkout -b pco-release--internal-rc
            git commit --allow-empty -m "New release branch"
          fi
      - run: git rebase origin/main --strategy-option=theirs
      - run: git push -f --set-upstream origin pco-release--internal-rc
      - run: ./node_modules/.bin/lerna publish --conventional-prerelease --conventionalCommits --createRelease=github --preid=rc --dist-tag=next --summary-file -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo packages=$(cat ./lerna-publish-summary.json) >> $GITHUB_OUTPUT
        id: published_packages
    outputs:
      releases: ${{ steps.published_packages.outputs.packages }}
  setup-release-pr:
    # needs: create-rc-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - uses: planningcenter/pco-release-action/release-by-pr-lerna@km/lerna
        id: release_by_pr
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      pull_request_id: ${{ steps.release_by_pr.outputs.pull_request_id }}
  report-rc-info:
    needs: [setup-release-pr, create-rc-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ needs.setup-release-pr.outputs.pull_request_id }}
          RELEASES: ${{ needs.create-rc-release.outputs.releases }}
        with:
          script: |
            if (!process.env.RELEASES || !process.env.PR_NUMBER) return
            const header = `## Release Candidate(s) successfully created`
            const releases = JSON.parse(process.env.RELEASES)
            const body = releases.map(release => `- \`${release.packageName}\` @ ${release.version}`).join("\n")

            github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${header}
                ${body}`
            });
