name: PCO-Release - Lerna Release PR
on:
  workflow_call:

jobs:
  create-rc-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PLANNINGCENTER_NPM_TOKEN }}
      - run: yarn install
      - run: ./node_modules/.bin/lerna publish --canary --conventional-prerelease --conventionalCommits --preid=rc --dist-tag=next --json -y
        id: lerna_publish
    outputs:
      releases: ${{ steps.lerna_publish.outputs }}
  setup-release-branch:
    needs: create-rc-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: |
          if git rev-parse --verify pco-release--internal > /dev/null 2>&1; then
            git checkout pco-release--internal
          else
            git checkout -b pco-release--internal
            git commit --allow-empty -m "New release branch"
          fi
      - run: git rebase origin/main --strategy-option=theirs
      - run: git push -f --set-upstream origin pco-release--internal
