name: PCO-Release - Lerna Release PR
on:
  workflow_call:

jobs:
  create-rc-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PLANNINGCENTER_NPM_TOKEN }}
      - run: yarn install
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: |
          if git rev-parse --verify pco-release--internal > /dev/null 2>&1; then
            git checkout pco-release--internal
          else
            git checkout -b pco-release--internal
            git commit --allow-empty -m "New release branch"
          fi
      - run: git rebase origin/main --strategy-option=theirs
      - run: git push -f --set-upstream origin pco-release--internal
      - run: |
          output = $(./node_modules/.bin/lerna publish --conventional-prerelease --conventionalCommits --preid=rc --dist-tag=next --json -y)
          echo "inlinereleases=$output" >> $GITHUB_OUTPUT
        id: lerna_publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      releases: ${{ steps.lerna_publish.outputs.stdout }}
      inlinereleases: ${{ steps.lerna_publish.outputs.inlinereleases }}
  setup-release-branch:
    needs: create-rc-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     ref: main
      #     fetch-depth: 0
      #     fetch-tags: true
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: "20"
      #     cache: "yarn"
      # - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      # - run: git config --global user.name "github-actions[bot]"
      # - run: |
      #     if git rev-parse --verify pco-release--internal > /dev/null 2>&1; then
      #       git checkout pco-release--internal
      #     else
      #       git checkout -b pco-release--internal
      #       git commit --allow-empty -m "New release branch"
      #     fi
      # - run: git rebase origin/main --strategy-option=theirs
      # - run: git push -f --set-upstream origin pco-release--internal
      - run: 'echo "Lerna publish output: ${{ needs.create-rc-release.outputs.releases }}"'
      - run: 'echo "Lerna publish output: ${{ needs.create-rc-release.outputs.inlinereleases }}"'
